### ISSUE TITLE
May be a typo in test/jason2.jl

### ISSUE THREAD

**Issue by sarvghotra** [quinnj/Endpoints.jl#1]
[Here](https://github.com/quinnj/Endpoints.jl/blob/master/test/json2.jl#L9)  `end` is missing.

Also, `type` has been depreciated. So, shall we change it to `mutable struct` ?

**Comment by quinnj** [comment]
Good catches; yes, both good changes to make.

**Comment by sarvghotra** [comment]
Thanks, I'll fix it right away.

**Comment by sarvghotra** [comment]
Still there are some issues in test/jason2.jl file. On running the file it throws `io not defined` at line 46. `try` and `catch` would be a good practice here.

**Comment by sarvghotra** [comment]
@quinnj Can you please take a look at this ?

**Comment by quinnj** [comment]
Ok, just pushed a commit that gets all tests passing for me.
