### ISSUE TITLE
Type Request has no field resource

### ISSUE THREAD

**Issue by sarvghotra** [quinnj/Endpoints.jl#3]
Running the server throws an error: `[HTTP - 2017-06-08T22:46:08.421]: ErrorException("type Request has no field resource")`

It's coming from this [line](https://github.com/quinnj/Endpoints.jl/blob/master/src/Endpoints.jl#L160).

**Comment by quinnj** [comment]
yeah, that should be changed to `HTTP.resource(HTTP.uri(req))`

**Comment by quinnj** [comment]
Fixed this.
